listen_addr = ":3000"
data_dir = "/Some/Dir"
library_dir = "/Some/Dir/With/Music" # Example: /home/USER/Music
username = "admin" # Username of the first user
initial_password = "admin" # Initial Password for user (should change after first login)
jwt_secret = "" # Example: openssl rand -base64 32
