// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

export const PostAlbum = z.object({
  id: z.string(),
});
export type PostAlbum = z.infer<typeof PostAlbum>;

export const PostAlbumBody = z.object({
  name: z.string(),
  artist: z.string(),
});
export type PostAlbumBody = z.infer<typeof PostAlbumBody>;

